SELECT
    (SELECT COUNT(MediumID) FROM digitalesmedium) AS ANZAHL_DIGITALER_MEDIEN,
    (SELECT COUNT(MediumID) FROM analogesmedium JOIN ausleihe USING (MediumID) )  AS ANZAHL_ANALOGEN_MEDIEN_AUSLEIHE,
    (SELECT COUNT(MediumID) FROM analogesmedium JOIN lieferung USING (MediumID) )  AS ANZAHL_ANALOGEN_MEDIEN_LIEFERUNG
